### PR TITLE
[SERV-407] Add Helm Logic for libcalproxy

### PR DESCRIPTION
**Pull request by cachemeoutside**

### CODE REVIEW

**Review by DRickard — APPROVED** [review]

**Comment by markmatney** [comment]
Any Helm commands that we can run locally to sanity check? I tried linting and got this:

```
$ helm lint libcalproxy/
==> Linting libcalproxy/
[ERROR] Chart.yaml: version '${chart.version}' is not a valid SemVer
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: validation: chart.metadata.version "${chart.version}" is invalid
[ERROR] : unable to load chart
	validation: chart.metadata.version "${chart.version}" is invalid

Error: 1 chart(s) linted, 1 chart(s) failed
```

**Comment by markmatney** [comment]
Any Helm commands that we can run locally to sanity check? I tried linting and got this:

```
$ helm lint libcalproxy/
==> Linting libcalproxy/
[ERROR] Chart.yaml: version '${chart.version}' is not a valid SemVer
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: validation: chart.metadata.version "${chart.version}" is invalid
[ERROR] : unable to load chart
	validation: chart.metadata.version "${chart.version}" is invalid

Error: 1 chart(s) linted, 1 chart(s) failed
```

**Comment by cachemeoutside** [comment]
I actually thought about adding a test using {{helm lint}} and {{helm template}}. That error is expected, because the {{helm-maven-plugin}} will actually substitute values through the usage of properties.

The end goal is to match these pointers to ${revision} as that is dynamically set on the release workflow.

**Comment by cachemeoutside** [comment]
Forgot to add that the helm maven plugin has `lint` and `template` features. This ticket is to just add the logic in place.

**Comment by cachemeoutside** [comment]
Here's an example of a lint/template command using the maven helm plugin in the next PR:

```
mvn -Drevision=0.0.7 -DskipSnapshots=false org.codehaus.mojo:build-helper-maven-plugin:regex-property com.deviceinsight.helm:helm-maven-plugin:2.10.0:lint
mvn -Drevision=0.0.7 -DskipSnapshots=false org.codehaus.mojo:build-helper-maven-plugin:regex-property com.deviceinsight.helm:helm-maven-plugin:2.10.0:template
```

**Review by markmatney — APPROVED** [review]

**Pull request merged**
